CREATE TABLE address (
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city character varying(255),
    country character varying(255),
    postal_code character varying(255),
    street character varying(255),
    CONSTRAINT address_country_check CHECK (country IN ('FRANCE', 'ITALY', 'SPAIN', 'UNITED_STATES'))
);

CREATE TABLE agency (
    agency_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    address_id integer
);

CREATE TABLE app_user (
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birthdate timestamp(6) without time zone,
    email character varying(255),
    firstname character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    role character varying(255),
    address_id integer,
    CONSTRAINT app_user_role_check CHECK (role IN ('CUSTOMER', 'SUPPORT'))
);

CREATE TABLE chat_message (
    chat_message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    text character varying(255),
    user_id integer NOT NULL,
    support_request_id integer NOT NULL
);

CREATE TABLE rental_offer (
    rental_offer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    end_date_time timestamp(6) without time zone,
    price real NOT NULL,
    start_date_time timestamp(6) without time zone,
    vehicle_category character varying(255),
    CONSTRAINT rental_offer_vehicle_category_check CHECK (vehicle_category IN ('SMALL_CAR', 'MEDIUM_CAR', 'LARGE_CAR'))
);

CREATE TABLE reservation (
    reservation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    price real NOT NULL,
    reservation_date_time timestamp(6) without time zone,
    reservation_status character varying(255),
    updated_at timestamp(6) without time zone,
    rental_offer_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT reservation_reservation_status_check CHECK (reservation_status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE support_request (
    support_request_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    support_request_status character varying(255),
    user_id integer NOT NULL,
    CONSTRAINT support_request_support_request_status_check CHECK (support_request_status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE video_call (
    video_call_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ended_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    support_request_id integer NOT NULL
);

CREATE TABLE web_message (
    web_message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    text character varying(255),
    support_request_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE ONLY address
    ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);

ALTER TABLE ONLY agency
    ADD CONSTRAINT agency_pkey PRIMARY KEY (agency_id);

ALTER TABLE ONLY app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (chat_message_id);

ALTER TABLE ONLY rental_offer
    ADD CONSTRAINT rental_offer_pkey PRIMARY KEY (rental_offer_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id);

ALTER TABLE ONLY support_request
    ADD CONSTRAINT support_request_pkey PRIMARY KEY (support_request_id);

ALTER TABLE ONLY video_call
    ADD CONSTRAINT video_call_pkey PRIMARY KEY (video_call_id);

ALTER TABLE ONLY web_message
    ADD CONSTRAINT web_message_pkey PRIMARY KEY (web_message_id);

ALTER TABLE ONLY support_request
    ADD CONSTRAINT fk4118qq5ulpy8n0rmaed6sno2t FOREIGN KEY (user_id) REFERENCES app_user(user_id);

ALTER TABLE ONLY web_message
    ADD CONSTRAINT fk496vkafhevdf4ppip3l6w06n2 FOREIGN KEY (user_id) REFERENCES app_user(user_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT fk60brs1nipkb3fdfbbonfy3jt2 FOREIGN KEY (rental_offer_id) REFERENCES rental_offer(rental_offer_id);

ALTER TABLE ONLY chat_message
    ADD CONSTRAINT fk97022dcuxcksytm2l2gyay4y FOREIGN KEY (user_id) REFERENCES app_user(user_id);

ALTER TABLE ONLY video_call
    ADD CONSTRAINT fkaril2casn3wkl9068j17pmh6p FOREIGN KEY (support_request_id) REFERENCES support_request(support_request_id);

ALTER TABLE ONLY agency
    ADD CONSTRAINT fkiqovy0gm1lebgwor5g2kdfcmk FOREIGN KEY (address_id) REFERENCES address(address_id);

ALTER TABLE ONLY app_user
    ADD CONSTRAINT fkl68nwoh0q1mcmgf9qx9h12miw FOREIGN KEY (address_id) REFERENCES address(address_id);

ALTER TABLE ONLY web_message
    ADD CONSTRAINT fkljmecfjxe6e3pgui610grn1gt FOREIGN KEY (support_request_id) REFERENCES support_request(support_request_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT fkm25r28103jb9lske61acewdlf FOREIGN KEY (user_id) REFERENCES app_user(user_id);

ALTER TABLE ONLY chat_message
    ADD CONSTRAINT fkpq7hhn9otxuhwsux1tej6vklk FOREIGN KEY (support_request_id) REFERENCES support_request(support_request_id);

CREATE INDEX idx_agency_address_id ON agency(address_id);

CREATE INDEX idx_app_user_address_id ON app_user(address_id);

CREATE INDEX idx_chat_message_user_id ON chat_message(user_id);

CREATE INDEX idx_chat_message_support_request_id ON chat_message(support_request_id);

CREATE INDEX idx_reservation_rental_offer_id ON reservation(rental_offer_id);

CREATE INDEX idx_reservation_user_id ON reservation(user_id);

CREATE INDEX idx_support_request_user_id ON support_request(user_id);

CREATE INDEX idx_video_call_support_request_id ON video_call(support_request_id);

CREATE INDEX idx_web_message_support_request_id ON web_message(support_request_id);

CREATE INDEX idx_web_message_user_id ON web_message(user_id);
