CREATE TABLE address (
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city character varying(255),
    country character varying(255),
    postal_code character varying(255),
    street character varying(255),
    CONSTRAINT address_country_check CHECK (country IN ('FRANCE', 'ITALY', 'SPAIN', 'UNITED_STATES'))
);

CREATE TABLE agency (
    address_id integer,
    agency_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    name character varying(255),
    phone character varying(255)
);

CREATE TABLE app_user (
    address_id integer,
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birthdate timestamp(6) without time zone,
    email character varying(255),
    firstname character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    role character varying(255),
    CONSTRAINT app_user_role_check CHECK (role IN ('CUSTOMER', 'SUPPORT'))
);

CREATE TABLE customer_message (
    customer_message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    text character varying(255)
);

CREATE TABLE rental_offer (
    price real NOT NULL,
    rental_offer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    end_date_time timestamp(6) without time zone,
    start_date_time timestamp(6) without time zone,
    vehicle_category character varying(255),
    CONSTRAINT rental_offer_vehicle_category_check CHECK (vehicle_category IN ('M', 'N', 'E', 'H', 'C', 'D'))
);

CREATE TABLE reservation (
    price real NOT NULL,
    rental_offer_id integer NOT NULL,
    reservation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    reservation_date_time timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    reservation_status character varying(255),
    CONSTRAINT reservation_reservation_status_check CHECK (reservation_status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE vehicle_classification (
    vehicle_classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vehicle_category character varying(255),
    vehicle_fuel_air_cond character varying(255),
    vehicle_transmission_drive character varying(255),
    vehicle_type character varying(255),
    CONSTRAINT vehicle_classification_vehicle_category_check CHECK (vehicle_category IN ('M', 'N', 'E', 'H', 'C', 'D')),
    CONSTRAINT vehicle_classification_vehicle_fuel_air_cond_check CHECK (vehicle_fuel_air_cond IN ('R', 'N', 'D', 'Q', 'H', 'I')),
    CONSTRAINT vehicle_classification_vehicle_transmission_drive_check CHECK (vehicle_transmission_drive IN ('M', 'N', 'C', 'A', 'B', 'D')),
    CONSTRAINT vehicle_classification_vehicle_type_check CHECK (vehicle_type IN ('B', 'C', 'D', 'W', 'V', 'L'))
);

ALTER TABLE ONLY address
    ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);

ALTER TABLE ONLY agency
    ADD CONSTRAINT agency_pkey PRIMARY KEY (agency_id);

ALTER TABLE ONLY app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY customer_message
    ADD CONSTRAINT customer_message_pkey PRIMARY KEY (customer_message_id);

ALTER TABLE ONLY rental_offer
    ADD CONSTRAINT rental_offer_pkey PRIMARY KEY (rental_offer_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id);

ALTER TABLE ONLY vehicle_classification
    ADD CONSTRAINT vehicle_classification_pkey PRIMARY KEY (vehicle_classification_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT fk60brs1nipkb3fdfbbonfy3jt2 FOREIGN KEY (rental_offer_id) REFERENCES rental_offer(rental_offer_id);

ALTER TABLE ONLY customer_message
    ADD CONSTRAINT fkbk62f6x0u6uvwn7xigk0077wq FOREIGN KEY (user_id) REFERENCES app_user(user_id);

ALTER TABLE ONLY agency
    ADD CONSTRAINT fkiqovy0gm1lebgwor5g2kdfcmk FOREIGN KEY (address_id) REFERENCES address(address_id);

ALTER TABLE ONLY app_user
    ADD CONSTRAINT fkl68nwoh0q1mcmgf9qx9h12miw FOREIGN KEY (address_id) REFERENCES address(address_id);

ALTER TABLE ONLY reservation
    ADD CONSTRAINT fkm25r28103jb9lske61acewdlf FOREIGN KEY (user_id) REFERENCES app_user(user_id);